version: "3.8"
services:
#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - 6379:6379
#    networks:
#      - java_network
  pushnotification:
    container_name: pushnotification
    image: pushnotification:1.0
    ports:
      - 8081:8081
#    depends_on:
#      - redis
    environment:
      - Profiles=docker
      - redis_host=redis
      - redis_port=6379
    networks:
      - java_network
networks:
  java_network:
    name: java_network

