spring:
  application:
    name: Profiles
  profiles:
    active: ${profiles}
#info:
#  name: ${spring.application.name}
#  description: Push Notification
#  environment: ${spring.profiles.active}
#  version: 1.0.0
