spring:
  application:
    name: swipepay-cloud
  profiles:
#    active: ${profiles}
    active: dev
#info:
#  name: ${spring.application.name}
#  description: Push Notification
#  environment: ${spring.profiles.active}
#  version: 1.0.0
